# .buildkite/pipeline.yml
steps:
  - label: ":construction_worker: Build"
    command: |
      python -m py_compile sources/add2vals.py sources/calc.py
      ls sources/__pycache__  # Verificar los archivos compilados
    plugins:
      - docker#v3.8.0:
          image: "python:3.12.1-alpine3.19"
          always_pull: true
          workdir: "/workdir"
    artifact_paths: "sources/*.py*"
  - wait

  - label: ":white_check_mark: Test"
    command: "py.test --junit-xml test-reports/results.xml sources/test_calc.py"
    plugins:
      - docker#v3.8.0:
          image: "qnib/pytest"
          always_pull: true
          workdir: "/workdir"
  - wait

  - label: ":rocket: Deliver"
    command: |
      python -m py_compile sources/add2vals.py  # Compilar add2vals.py
      ls sources/__pycache__  # Verificar que los archivos .pyc se generaron
      mkdir -p /workdir/deliver
      cp sources/__pycache__/add2vals* /workdir/deliver/  # Copiar el ejecutable compilado
    plugins:
      - docker#v3.8.0:
          image: "python:3.12.1-alpine3.19"
          always_pull: true
          workdir: "/workdir"
    artifact_paths: "/workdir/deliver/*"  # Asegúrate de que los artefactos estén en el directorio correcto
  - wait


