steps:
  - label: ":python: Build"
    plugins:
      - docker#v3.13.0:
          image: "python:2-alpine"
    commands:
      - python -m py_compile sources/add2vals.py sources/calc.py

  - label: ":pytest: Test"
    plugins:
      - docker#v3.13.0:
          image: "qnib/pytest"
    commands:
      - mkdir -p test-reports
      - py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py
      - cat test-reports/results.xml # Imprime los resultados de las pruebas
    artifacts:
      - test-reports/results.xml

  - label: ":package: Deliver"
    plugins:
      - docker#v3.13.0:
          image: "cdrx/pyinstaller-linux:python2"
    commands:
      - pyinstaller --onefile sources/add2vals.py
    artifacts:
      - dist/add2vals


