steps:
  - label: "Build"
    plugins:
      - docker#v3.12.0:
          image: "python:3.12.0-alpine3.18"
    command:
      - "python -m py_compile sources/add2vals.py sources/calc.py"
    artifact_paths:
      - "sources/*.py*"

  - label: "Test"
    plugins:
      - docker#v3.12.0:
          image: "qnib/pytest"
    command:
      - |
        py.test --junit-xml test-reports/results.xml sources/test_calc.py || true
    artifact_paths:
      - "test-reports/results.xml"

  - label: "Deliver"
    plugins:
      - docker#v3.12.0:
          image: "cdrx/pyinstaller-linux:python2"
    command:
      - mkdir -p build-output
      - mv sources/*.py* build-output
      - "docker run --rm -v $(pwd)/build-output:/src cdrx/pyinstaller-linux:python2 pyinstaller -F add2vals.py"
    artifact_paths:
      - "build-output/dist/add2vals"

  - wait


